/**
 * build-seo.mjs
 * ─────────────────────────────────────────────────────────────────────────
 * Auto-generates SEO content for shop.html and every category/*.html page,
 * using the SAME product data and the SAME card-rendering function the
 * live site already uses (imported directly from shop-engine.js). This
 * guarantees the static HTML always matches what visitors actually see —
 * nothing is re-implemented or duplicated by hand.
 *
 * What it does, per page:
 *   1. Fills <div id="productGrid"> with real, pre-rendered product cards
 *      (between SEO:PRODUCTS markers) so search engines see real content
 *      immediately, before any JavaScript runs.
 *   2. Fills the page's "ItemList" JSON-LD block with real product data
 *      (name, image, price, url, rating) so Google can show rich results.
 *
 * SAFE TO RE-RUN ANY NUMBER OF TIMES:
 *   - The product grid is only ever written between two unique HTML
 *     comment markers, located by plain string search (not regex), so
 *     nested </div> tags inside product cards can never confuse it.
 *   - The JSON-LD block is parsed as real JSON (not string-matched), its
 *     itemListElement is overwritten, and it's written back — so it
 *     always reflects the current contents of products.js.
 *
 * The client-side engine (shop-engine.js) still runs exactly as before —
 * it simply replaces this static content with its own interactive render
 * on page load (filters/sort/search/pagination all keep working).
 *
 * HOW TO RUN
 * ────────────
 *   node scripts/build-seo.mjs
 *
 * This is also run automatically by GitHub Actions on every push that
 * touches assets/js/products.js — see .github/workflows/build-seo.yml
 * ─────────────────────────────────────────────────────────────────────────
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

import { products } from '../assets/js/products.js';
import { renderCard, buildAffiliateLink } from '../assets/js/shop-engine.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '..');
const SITE_URL = 'https://everydaybeautyproducts.com';

// Every page this script touches, and which products belong on it.
// 'all' = every product (shop.html); otherwise the category slug must
// match the `category` field used in products.js.
const PAGES = [
  { file: 'shop.html', category: 'all' },
  { file: 'category/skin-care.html', category: 'skin-care' },
  { file: 'category/makeup.html', category: 'makeup' },
  { file: 'category/hair-care.html', category: 'hair-care' },
  { file: 'category/fragrance.html', category: 'fragrance' },
  { file: 'category/foot-hand-nail.html', category: 'foot-hand-nail' },
  { file: 'category/personal-care.html', category: 'personal-care' },
];

// Unique marker strings. Because these exact strings never appear
// anywhere else in the page, we can find them with a plain indexOf()
// instead of a regex — this avoids any risk of a regex accidentally
// matching a nested </div> from inside a product card.
const MARKER_START = '<!-- SEO:PRODUCTS:START — auto-generated by scripts/build-seo.mjs, do not edit by hand -->';
const MARKER_END   = '<!-- SEO:PRODUCTS:END -->';
const EMPTY_GRID   = '<div class="product-grid" id="productGrid"></div>';

const LDJSON_RE = /<script type="application\/ld\+json">([\s\S]*?)<\/script>/g;

// =============================================
// FAQ SCHEMA (FAQPage JSON-LD) — shop.html + category pages
// ─────────────────────────────────────────────
// Same approach as scripts/build-blog-seo.mjs: the FAQ accordion markup
// (.faq-item / .faq-q / .faq-a) is hand-authored directly in each page's
// HTML, so this reads the FAQPage schema straight out of that SAME
// content instead of trusting a separately hand-written schema block —
// which is exactly what let a category page's schema silently drift out
// of sync with its own visible FAQ in the past (a question added to the
// page later never got added to the old hand-written schema). Re-running
// this always makes the schema an exact mirror of whatever .faq-item
// blocks currently exist on that page — nothing to remember to update by
// hand, ever again.
// =============================================
const FAQ_ITEM_RE = /<div class="faq-item"[^>]*>\s*<div class="faq-q">([\s\S]*?)<\/div>\s*<div class="faq-a">([\s\S]*?)<\/div>\s*<\/div>/g;
// Matches ANY ld+json block, pretty-printed or minified — parsed as real
// JSON below, so an existing FAQPage block is found/replaced regardless
// of formatting (never left behind as a stray duplicate).
const LDJSON_BLOCK_RE = /<script type="application\/ld\+json">([\s\S]*?)<\/script>\n?/g;

function toPlainText(innerHtml) {
  return innerHtml
    .replace(/<span class="arrow">[\s\S]*?<\/span>/g, '')
    .replace(/<[^>]+>/g, '')
    .replace(/&amp;/g, '&').replace(/&lt;/g, '<').replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"').replace(/&#39;/g, "'")
    .replace(/\s+/g, ' ')
    .trim();
}

function extractFaqs(html) {
  const faqs = [];
  for (const match of html.matchAll(FAQ_ITEM_RE)) {
    const question = toPlainText(match[1]);
    const answer = toPlainText(match[2]);
    if (question && answer) faqs.push({ question, answer });
  }
  return faqs;
}

function buildFaqPageScript(faqs) {
  const schema = {
    '@context': 'https://schema.org',
    '@type': 'FAQPage',
    mainEntity: faqs.map(f => ({
      '@type': 'Question',
      name: f.question,
      acceptedAnswer: { '@type': 'Answer', text: f.answer },
    })),
  };
  return `<script type="application/ld+json">${JSON.stringify(schema)}</script>`;
}

// Removes every existing FAQPage block (any formatting) and inserts
// exactly one fresh block built from the page's current .faq-item
// markup. shop.html has no FAQ section, so this is a safe no-op there.
function injectFaqSchema(html, fileLabel) {
  const faqs = extractFaqs(html);

  let removedCount = 0;
  let withoutFaqPage = html.replace(LDJSON_BLOCK_RE, (fullMatch, jsonText) => {
    try {
      const obj = JSON.parse(jsonText);
      if (obj['@type'] === 'FAQPage') { removedCount++; return ''; }
    } catch {
      // Not valid JSON — not ours, leave untouched.
    }
    return fullMatch;
  });

  if (removedCount > 1) {
    console.warn(`  \u26a0 ${fileLabel}: found ${removedCount} duplicate FAQPage blocks — collapsed down to 1`);
  }

  if (!faqs.length) return withoutFaqPage;

  if (!withoutFaqPage.includes('</head>')) {
    console.warn(`  \u26a0 ${fileLabel}: no </head> found — FAQPage schema skipped`);
    return withoutFaqPage;
  }
  console.log(`  \u2022 ${fileLabel}: FAQPage schema (${faqs.length} question${faqs.length === 1 ? '' : 's'})`);
  const scriptTag = buildFaqPageScript(faqs);
  return withoutFaqPage.replace('</head>', `${scriptTag}\n</head>`);
}

function productsForPage(category) {
  // Keep the same default order the live site uses ("Most Popular" = original order)
  return category === 'all'
    ? products
    : products.filter(p => p.category === category);
}

function buildItemListElements(pageProducts) {
  return pageProducts.map((p, i) => ({
    '@type': 'ListItem',
    position: i + 1,
    item: {
      '@type': 'Product',
      name: p.name,
      image: `${SITE_URL}${p.img}`,
      description: p.excerpt,
      brand: { '@type': 'Brand', name: p.brand },
      url: buildAffiliateLink(p.asin),
      // NOTE: no aggregateRating here on purpose. p.rating/p.reviews are
      // Amazon's numbers, not reviews collected on this site, and Google's
      // structured data guidelines disallow using third-party ratings in
      // your own review/aggregateRating markup (risk of a manual action).
      offers: {
        '@type': 'Offer',
        priceCurrency: 'USD',
        price: p.price.toFixed(2),
        availability: 'https://schema.org/InStock',
        url: buildAffiliateLink(p.asin),
      },
    },
  }));
}

// Parses every JSON-LD <script> block on the page, finds the ONE that has
// a "mainEntity": { "@type": "ItemList" } shape, and overwrites its
// itemListElement — regardless of whether it's empty (first run) or
// already has old data in it (subsequent runs).
function injectItemList(html, pageProducts, fileLabel) {
  const itemListElement = buildItemListElements(pageProducts);
  let replaced = false;

  const newHtml = html.replace(LDJSON_RE, (fullMatch, jsonText) => {
    let obj;
    try {
      obj = JSON.parse(jsonText);
    } catch (err) {
      console.warn(`  \u26a0 ${fileLabel}: found a JSON-LD block that isn't valid JSON — left untouched`);
      return fullMatch;
    }
    if (obj && obj.mainEntity && obj.mainEntity['@type'] === 'ItemList') {
      obj.mainEntity.itemListElement = itemListElement;
      replaced = true;
      return `<script type="application/ld+json">\n${JSON.stringify(obj, null, 2)}\n</script>`;
    }
    return fullMatch;
  });

  if (!replaced) {
    console.warn(`  \u26a0 ${fileLabel}: no "ItemList" JSON-LD block found — skipped (page structure may have changed)`);
  }
  return newHtml;
}

function injectProductGrid(html, pageProducts, fileLabel) {
  const cardsHtml = pageProducts.map(renderCard).join('\n');

  const startIdx = html.indexOf(MARKER_START);
  const endIdx = html.indexOf(MARKER_END);

  if (startIdx !== -1 && endIdx !== -1 && endIdx > startIdx) {
    // Re-run: this page already has our markers from a previous run.
    // Replace ONLY the exact span between them — everything else
    // (the surrounding <div id="productGrid"> and the rest of the page)
    // is left completely untouched.
    const before = html.slice(0, startIdx);
    const after = html.slice(endIdx + MARKER_END.length);
    return `${before}${MARKER_START}\n${cardsHtml}\n${MARKER_END}${after}`;
  }

  if (html.includes(EMPTY_GRID)) {
    // First run: grid is still empty exactly as shipped. Wrap the new
    // cards in the markers so future runs can find them safely.
    const block = `<div class="product-grid" id="productGrid">\n${MARKER_START}\n${cardsHtml}\n${MARKER_END}\n</div>`;
    return html.replace(EMPTY_GRID, block);
  }

  console.warn(`  \u26a0 ${fileLabel}: could not find #productGrid div or existing markers — skipped (page structure may have changed)`);
  return html;
}

function buildPage({ file, category }) {
  const filePath = path.join(ROOT, file);
  const original = readFileSync(filePath, 'utf8');
  const pageProducts = productsForPage(category);

  let html = original;
  html = injectItemList(html, pageProducts, file);
  html = injectProductGrid(html, pageProducts, file);
  html = injectFaqSchema(html, file);

  if (html !== original) {
    writeFileSync(filePath, html, 'utf8');
    console.log(`\u2714 ${file} — ${pageProducts.length} product(s) written`);
  } else {
    console.log(`… ${file} — no changes`);
  }
}

console.log(`Building SEO content from ${products.length} product(s) in products.js\n`);
for (const page of PAGES) {
  buildPage(page);
}
console.log('\nDone.');
